version: "3.0"
services:
  image_cls_terror:
    image: ${HUB_DOMAIN}/mlmodel/image_classification:${REST_TAG}
    container_name: image_cls_terror
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5021:80"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CPU_NUM=2
      - BATCH_SIZE=8
      - SERVICE_NAME=image_cls_terror
      - ETCD_HOST=${ETCD_HOST}
      - SERVICE_HOST=${SERVICE_HOST}
      - SERVICE_PORT=5021
      - SERVICE_ENDPOINT=machineapi_content
      - VERSION=${TERROR_CLS_VERSION}
      - USE_STREAMER=1
    runtime: nvidia
    volumes:
      # mount this volume for log
      - app_logs:/codes/volume_logs
      - models:/models

  image_cls_eroticext:
    image: ${HUB_DOMAIN}/mlmodel/image_classification:${REST_TAG}
    container_name: image_cls_eroticext
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5023:80"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CPU_NUM=2
      - BATCH_SIZE=8
      - SERVICE_NAME=image_cls_eroticext
      - ETCD_HOST=${ETCD_HOST}
      - SERVICE_HOST=${SERVICE_HOST}
      - SERVICE_PORT=5023
      - SERVICE_ENDPOINT=machineapi_content
      - VERSION=${EROTICEXT_CLS_VERSION}
      - USE_STREAMER=1
    runtime: nvidia
    volumes:
      # mount this volume for log
      - app_logs:/codes/volume_logs
      - models:/models

volumes:
  app_logs:
    external: true
  models:
    driver: local
    driver_opts:
      o: bind
      type: none
      # model weight path
      device: /home/ubuntu/models
