apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-image-classification      # 图像分类
  namespace: aiengine-${ENV}
  labels:
    app: engine-image-classification        # 必须和 service 定义相同的label
spec:
  replicas: ${REPLICAS}            # 节点数
  selector:
    matchLabels:
      app: engine-image-classification
  template:
    metadata:
      labels:
        app: engine-image-classification
    spec:
#      nodeSelector:
#        accelerator: nvidia-t4
      containers:
        - name: image-cls-terror       # 图像暴恐分类
          imagePullPolicy: Always
          image: swr.cn-north-4.myhuaweicloud.com/mlmodel/image_classification:${REST_IMAGE_TAG}
          ports:
            - containerPort: 5021
              protocol: TCP
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: BATCH_SIZE
              value: "8"
            - name: CPU_NUM
              value: "2"
            - name: SERVICE_NAME
              value: image_cls_terror
            - name: ETCD_HOST
              value: ${ETCD_HOST}
            - name: SERVICE_HOST
              value: ${SERVICE_HOST}
            - name: SERVICE_PORT
              value: "5021"
            - name: SERVICE_ENDPOINT
              value: machineapi_content
            - name: VERSION
              value: ${TERROR_CLS_VERSION}
            - name: USE_STREAMER
              value: "1"
          resources:
            requests:
              nvidia.com/gpu: 0.1   # 申请GPU的数量
            limits:
              nvidia.com/gpu: 0.1   # GPU数量的使用上限
          volumeMounts:
            - name: nfs-volume
              mountPath: /models
#        - name: image-cls-eroticext       # 色情补充分类
#          imagePullPolicy: Always
#          image: swr.cn-north-4.myhuaweicloud.com/mlmodel/image_classification:${REST_IMAGE_TAG}
#          ports:
#            - containerPort: 5023
#          env:
#            - name: NVIDIA_VISIBLE_DEVICES
#              value: all
#            - name: BATCH_SIZE
#              value: "8"
#            - name: CPU_NUM
#              value: "2"
#            - name: SERVICE_NAME
#              value: image_cls_eroticext
#            - name: ETCD_HOST
#              value: ${ETCD_HOST}
#            - name: SERVICE_HOST
#              value: ${SERVICE_HOST}
#            - name: SERVICE_PORT
#              value: "5023"
#            - name: SERVICE_ENDPOINT
#              value: machineapi_content
#            - name: VERSION
#              value: ${EROTICEXT_CLS_VERSION}
#            - name: USE_STREAMER
#              value: "1"
#          resources:
#            requests:
#              nvidia.com/gpu: 0.1   # 申请GPU的数量
#            limits:
#              nvidia.com/gpu: 0.1   # GPU数量的使用上限
#          volumeMounts:
#            - name: nfs-volume
#              mountPath: /models
      imagePullSecrets:
        - name: default-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              # - matchExpressions:
              #     - key: accelerator
              #       operator: In
              #       values:
              #         - "nvidia-rtx5000"
              #         - "nvidia-t4"
                  - key: engine.role         #固定资源组
                    operator: In
                    values:
                      - "imagecls"
      volumes:
        - name: nfs-volume
          nfs:
            server: 10.28.0.136
            path: /home/ubuntu/AIMODELS